error_on_failure: false

error_on_warning: false

vignettes:
  active: true
  flesch-kincaid:
    active: true
    warn: 50
    fail: 30
  length:
    active: true
    too_long:
      active: true
      warn: 2000
      fail: 3000
    too_short:
      active: true
      warn: 100
      fail: 0
  problem_words:
    active: false
  image_alt_text:
    active: false

functions:
  active: false
